name: memogenerator
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.7
  provider: ^6.0.5
  google_fonts: ^4.0.3
  uuid: ^3.0.7
  json_annotation: ^4.8.1
  shared_preferences: ^2.1.1
  equatable: ^2.0.5
  image_picker: ^0.8.7+5
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  build_runner: ^2.4.4

flutter:
  uses-material-design: true
